### ISSUE TITLE
Warning: Umbrella header for module 'Highcharts' does not include headers

### ISSUE THREAD

**Issue by martinpilch** [highcharts/highcharts-ios#182]
Hi,
I'm getting following warnings when compiling my project:

```
Umbrella header for module 'Highcharts' does not include header 'HISeriesSunburstDataLabelsOptionsObject.h'
Umbrella header for module 'Highcharts' does not include header 'HIPlotPieDataLabelsOptionsObject.h'
Umbrella header for module 'Highcharts' does not include header 'HIPlotPackedBubbleDataLabelsOptionsObject.h'
Umbrella header for module 'Highcharts' does not include header 'HIPlotAreaRangeDataLabelsOptionsObject.h'
Umbrella header for module 'Highcharts' does not include header 'HIPlotSankeyDataLabelsOptionsObject.h'
Umbrella header for module 'Highcharts' does not include header 'HIPlotNetworkDataLabelsOptionsObject.h'
```

I use Xcode 10.2 (10E125) and my project is in Swift 5. I added `Highcharts` to the project manually and it happens for both development and release version of framework. 

Any ideas how to get rid of it?

**Comment by ihnatmoisieiev** [comment]
@martinpilch thank you for the reporting. We will investigate it as soon as possible.

**Comment by martinpilch** [comment]
Hi @ihnatmoisieiev. Any update on this?

**Comment by ihnatmoisieiev** [comment]
Hi @martinpilch, 
it would be investigated before releasing the next version. 
These are only warnings.

**Comment by ihnatmoisieiev** [comment]
@martinpilch the issue has been fixed in the latest release.

**Comment by martinpilch** [comment]
Thanks @ihnatmoisieiev for letting me know. Unfortunately I keep getting the warnings (even more of them):

```
Umbrella header for module 'Highcharts' does not include header 'HIFilter.h'
Umbrella header for module 'Highcharts' does not include header 'HIDataAccessibility.h'
Umbrella header for module 'Highcharts' does not include header 'HISeriesSunburstDataLabelsOptionsObject.h'
Umbrella header for module 'Highcharts' does not include header 'HISeriesAccessibility.h'
Umbrella header for module 'Highcharts' does not include header 'HIPlotPieDataLabelsOptionsObject.h'
Umbrella header for module 'Highcharts' does not include header 'HIExportingAccessibility.h'
Umbrella header for module 'Highcharts' does not include header 'HIPlotPackedBubbleDataLabelsOptionsObject.h'
Umbrella header for module 'Highcharts' does not include header 'HIItemCheckboxStyle.h'
Umbrella header for module 'Highcharts' does not include header 'HIPlotAreaRangeDataLabelsOptionsObject.h'
Umbrella header for module 'Highcharts' does not include header 'HIPlotSankeyDataLabelsOptionsObject.h'
Umbrella header for module 'Highcharts' does not include header 'HIPlotNetworkDataLabelsOptionsObject.h'
Umbrella header for module 'Highcharts' does not include header 'HIItems.h'
```

I deleted derived data, restared Xcode (Version 10.2 (10E125)) but still getting them

**Comment by ihnatmoisieiev** [comment]
@martinpilch did you update to the latest `7.1.2.1` version?

I don't see any warnings in the [HighFit](https://github.com/highcharts/highcharts-ios/tree/master/Example/HighFit/HighFit) with `7.1.2.1`.

**Comment by martinpilch** [comment]
@ihnatmoisieiev I had to make several clean builds and Xcode restarts to make it compiling without any warnings. Consider it fixed then. And thank you for your patience!
