### ISSUE TITLE
Labels are not displayed after migrating to 7.1.4

### ISSUE THREAD

**Issue by ergunkocak** [highcharts/highcharts-ios#233]
Hi,

I upgraded from 7.0.1 to 7.1.4. I use static libraries from git repo development and production.
Here is the problematic part from code: 

        let pie = HIPie()
        pie.size = 135
        pie.innerSize = "72%"
        pie.colors = [HIColor(hexValue: "ECDA9A"), HIColor(hexValue: "EE4E5A"), HIColor(hexValue: "2A5673"), HIColor(hexValue: "4F90A6"), HIColor(hexValue: "A9DBDA")]
        pie.data = pieChartSlices.map({ ["name": $0.name, "y":$0.y] })
        pie.borderColor = HIColor(hexValue: "f5f5f5")
        pie.borderWidth = 2

        let dataLabelsOptionsObject = HIDataLabelsOptionsObject()
        dataLabelsOptionsObject.enabled = true
        dataLabelsOptionsObject.format = "<span>{point.name}</span><br><span style=\"color: #A2A2A2;\">{point.percentage:.2f} %</span>"
        dataLabelsOptionsObject.useHTML = true
        dataLabelsOptionsObject.color = HIColor(hexValue: "151515")
        dataLabelsOptionsObject.style = HICSSObject()
        dataLabelsOptionsObject.style.fontWeight = "500"
        dataLabelsOptionsObject.style.fontSize = "10px"
        dataLabelsOptionsObject.connectorColor = HIColor(uiColor: .clear)
        dataLabelsOptionsObject.distance = 10
        dataLabelsOptionsObject.padding = 0
        dataLabelsOptionsObject.allowOverlap = true

        pie.dataLabels = [dataLabelsOptionsObject]

First of all :

dataLabelsOptionsObject.connectorColor = HIColor(uiColor: .clear)

line does not compile so i comment it out.

Second:

I get no labels : 
![Screenshot 2019-09-03 at 15 12 48](https://user-images.githubusercontent.com/610975/64176268-597aa100-ce5d-11e9-9b9b-c3765c21e932.png)

**Comment by ihnatmoisieiev** [comment]
Hi @ergunkocak,

thank you for reporting the issue. It would be fixed in the next release.

**Comment by ihnatmoisieiev** [comment]
It connected to https://github.com/highcharts/highcharts/issues/11761.

**Comment by ihnatmoisieiev** [comment]
@ergunkocak the issue has been fixed in the latest release.

**Comment by ergunkocak** [comment]
Hi @ihnatmoisieiev ,

I can see the labels again 👍 

But 

dataLabelsOptionsObject.connectorColor = HIColor(uiColor: .clear)

still does not work. How can assign clear color to connector color?

Best

**Comment by ergunkocak** [comment]
Found it :) 

dataLabelsOptionsObject.connectorColor = "00000000"

worked
