### ISSUE TITLE
How to set HeatMap borderWidth and Colour? (Swift)

### ISSUE THREAD

**Issue by StellarKuldeep** [highcharts/highcharts-ios#93]
I want to set Heatmap borderWidth and borderColor but there's no property like this.
```
var heatmap = HIHeatmap()
    heatmap.dataLabels = HIDataLabels()
    heatmap.dataLabels.enabled = NSNumber(booleanLiteral: true)
    heatmap.dataLabels.color = HIColor(hexValue: "000000")
    heatmap.enableMouseTracking = NSNumber(booleanLiteral: false)
    heatmap.data = [[0, 0, 10], [0, 1, 19], [0, 2, 8], [0, 3, 24], [0, 4, 67], [0, 5, 20],[0,6,34],[0,7,34234]]
```
How to do this?

**Comment by ihnatmoisieiev** [comment]
Hello @StellarKuldeep,
thank you for the reporting an issue. It will be fixed.
[https://github.com/highcharts/highcharts/issues/8259](https://github.com/highcharts/highcharts/issues/8259)

**Comment by ihnatmoisieiev** [comment]
@StellarKuldeep, it is fixed in the latest release.

**Comment by yakovsofer** [comment]
I still do not see Heatmap borderWidth and borderColor properties.

**Comment by ihnatmoisieiev** [comment]
@yakovsofer please try use `marker..lineWidth` and `marker.lineColor`, e.g.

```
heatmap.marker = HIMarker()
heatmap.marker.lineWidth = 3
heatmap.marker.lineColor = "green"
```
